// GENERATED by scripts/build-treatment-kb.mjs from docs/treatment-options-kb.md.
// Do not edit by hand: edit the markdown, then run `npm run kb:build`.

export const KB_VERSION = "v1.0" as const;

export const KB_OPTIONS = [
  {
    "id": "pd",
    "en": "Peritoneal dialysis (PD)",
    "zh": "腹膜透析"
  },
  {
    "id": "hd",
    "en": "Haemodialysis at a centre (HD)",
    "zh": "中心血液透析"
  },
  {
    "id": "tx",
    "en": "Kidney transplant",
    "zh": "肾脏移植"
  },
  {
    "id": "ckm",
    "en": "Conservative kidney management (care without dialysis)",
    "zh": "保守肾脏管理（不做透析的护理）"
  }
] as const;

export const KB_DIMENSIONS = [
  {
    "id": "independence",
    "en": "Managing my own care",
    "zh": "自己管理护理",
    "questions": [
      "values-1",
      "treatment-independence"
    ]
  },
  {
    "id": "flexibility",
    "en": "Flexible days vs a fixed routine",
    "zh": "时间灵活还是安排固定",
    "questions": [
      "treatment-priorities"
    ]
  },
  {
    "id": "work",
    "en": "Work and daily responsibilities",
    "zh": "工作和日常责任",
    "questions": [
      "values-1",
      "treatment-priorities"
    ]
  },
  {
    "id": "travel",
    "en": "Travel and overnight stays",
    "zh": "旅行和在外过夜",
    "questions": [
      "treatment-travel",
      "treatment-priorities"
    ]
  },
  {
    "id": "time",
    "en": "Time and trips spent on care",
    "zh": "花在护理上的时间和来回次数",
    "questions": [
      "treatment-priorities",
      "life-2"
    ]
  },
  {
    "id": "family",
    "en": "Help needed from family",
    "zh": "需要家人帮忙的程度",
    "questions": [
      "life-3",
      "values-1",
      "worries-1"
    ]
  },
  {
    "id": "home",
    "en": "Where care happens and my home",
    "zh": "在哪里接受护理和家里的条件",
    "questions": [
      "treatment-location"
    ]
  },
  {
    "id": "body",
    "en": "Effects on my body and physical demands",
    "zh": "对身体的影响和体力要求",
    "questions": [
      "treatment-mobility",
      "worries-1"
    ]
  },
  {
    "id": "comfort",
    "en": "Feeling comfortable day to day",
    "zh": "日常舒适感",
    "questions": [
      "values-1"
    ]
  },
  {
    "id": "longevity",
    "en": "How long I may live",
    "zh": "可能活多久",
    "questions": [
      "treatment-priorities"
    ]
  },
  {
    "id": "cost",
    "en": "Costs",
    "zh": "费用",
    "questions": [
      "worries-1"
    ]
  }
] as const;

export const KB_STATEMENTS = [
  {
    "id": "pd.summary.1",
    "option": "pd",
    "dimension": null,
    "tag": "practical",
    "en": "Dialysis done at home through a soft tube in your tummy. Cleaning fluid flows in, collects waste and extra water, and is then drained out.",
    "zh": "在家里通过肚子上的一条软管做透析。透析液流进肚子，带走废物和多余的水分，然后再排出来。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.summary.2",
    "option": "pd",
    "dimension": null,
    "tag": "practical",
    "en": "There are two ways: changing the fluid by hand a few times during the day, or using a machine that changes it at night while you sleep.",
    "zh": "有两种方式：白天用手换几次透析液，或者晚上睡觉时用机器自动换液。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "hd.summary.1",
    "option": "hd",
    "dimension": null,
    "tag": "practical",
    "en": "Your blood is cleaned by a machine at a dialysis centre, usually 3 times a week for about 4 hours each time.",
    "zh": "在透析中心用机器清洗血液，通常每周三次，每次大约四个小时。",
    "sources": [
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "hd.summary.2",
    "option": "hd",
    "dimension": null,
    "tag": "practical",
    "en": "Some NKF centres also offer evening sessions or overnight dialysis while you sleep.",
    "zh": "部分国家肾脏基金会（NKF）中心也提供傍晚时段，或在晚上睡觉时进行的夜间透析。",
    "sources": [
      "NKF-HD",
      "NKF-NOC"
    ],
    "gated": false
  },
  {
    "id": "tx.summary.1",
    "option": "tx",
    "dimension": null,
    "tag": "practical",
    "en": "An operation places a healthy kidney from a donor into your body. The donor may be a family member or close friend, or someone who has passed away.",
    "zh": "通过手术把一颗健康的肾脏放进您的身体。捐肾的人可以是家人或好朋友，也可以是已经过世的人。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "ckm.summary.1",
    "option": "ckm",
    "dimension": null,
    "tag": "practical",
    "en": "Care without dialysis. Your kidney team helps you manage symptoms with medicine, diet and other support, so you can live as well as possible.",
    "zh": "不做透析的护理方式。肾脏团队通过药物、饮食和其他支持帮助您控制症状，让您尽量生活得好。",
    "sources": [
      "KHA-G",
      "RRT"
    ],
    "gated": false
  },
  {
    "id": "ckm.summary.2",
    "option": "ckm",
    "dimension": null,
    "tag": "practical",
    "en": "It is a planned choice with ongoing care from your kidney team. It is not \"doing nothing\".",
    "zh": "这是一个有计划的选择，肾脏团队会一直照顾您。这并不是\"什么都不做\"。",
    "sources": [
      "MYK",
      "RRT"
    ],
    "gated": false
  },
  {
    "id": "common.suitability.1",
    "option": "common",
    "dimension": null,
    "tag": "practical",
    "en": "Not every option is suitable for everyone. Your care team will tell you which options are possible for you.",
    "zh": "不是每种方式都适合每个人。医疗团队会告诉您哪些方式适合您。",
    "sources": [
      "RRT"
    ],
    "gated": false
  },
  {
    "id": "common.nochoice.1",
    "option": "common",
    "dimension": null,
    "tag": "practical",
    "en": "There is no single right answer. People with similar health can make different choices.",
    "zh": "没有唯一正确的答案。健康情况相似的人，也可以做出不同的选择。",
    "sources": [
      "RRT"
    ],
    "gated": false
  },
  {
    "id": "common.change.1",
    "option": "common",
    "dimension": null,
    "tag": "practical",
    "en": "You can talk to your care team about changing your treatment later if your needs change.",
    "zh": "如果以后您的需要有变化，可以和医疗团队商量换一种治疗方式。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "common.ksc.1",
    "option": "common",
    "dimension": null,
    "tag": "practical",
    "en": "Kidney supportive care is available alongside your treatment. It helps with symptoms such as pain, itch and tiredness, gives emotional support, and helps you plan ahead.",
    "zh": "在治疗的同时，您也可以得到肾脏支持性护理。它帮助处理疼痛、瘙痒、疲倦等症状，提供情绪支持，并帮助您提前做好规划。",
    "sources": [
      "NKF-KSC",
      "RRT"
    ],
    "gated": false
  },
  {
    "id": "pd.independence.helps.1",
    "option": "pd",
    "dimension": "independence",
    "tag": "helps",
    "en": "You do the treatment yourself at home and plan it around your own day.",
    "zh": "您在家里自己做治疗，可以按照自己的作息来安排。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.independence.practical.1",
    "option": "pd",
    "dimension": "independence",
    "tag": "practical",
    "en": "The PD nurses train you, or a family member, to do it safely.",
    "zh": "腹膜透析护士会教您或您的家人如何安全地做。",
    "sources": [
      "NKF-PD",
      "VAN"
    ],
    "gated": false
  },
  {
    "id": "pd.independence.harder.1",
    "option": "pd",
    "dimension": "independence",
    "tag": "harder",
    "en": "It needs to be done every day, and the tube must be kept clean to prevent infection.",
    "zh": "需要每天做，而且软管要保持清洁，以免感染。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "hd.independence.helps.1",
    "option": "hd",
    "dimension": "independence",
    "tag": "helps",
    "en": "Nurses and staff at the centre do the treatment for you.",
    "zh": "由透析中心的护士和工作人员为您做治疗。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "hd.independence.harder.1",
    "option": "hd",
    "dimension": "independence",
    "tag": "harder",
    "en": "You follow the centre's fixed schedule rather than your own.",
    "zh": "您需要按照透析中心固定的时间安排，而不是自己的时间。",
    "sources": [
      "NKF-PD",
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "tx.independence.helps.1",
    "option": "tx",
    "dimension": "independence",
    "tag": "helps",
    "en": "If the new kidney works well, you no longer need dialysis and can manage daily life much as before.",
    "zh": "如果新肾脏运作良好，您就不需要再透析，可以像以前一样打理日常生活。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "tx.independence.harder.1",
    "option": "tx",
    "dimension": "independence",
    "tag": "harder",
    "en": "You must take anti-rejection medicine every day for the rest of your life.",
    "zh": "您需要一辈子每天服用抗排斥药物。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "tx.independence.practical.1",
    "option": "tx",
    "dimension": "independence",
    "tag": "practical",
    "en": "You will need regular check-ups at the transplant clinic.",
    "zh": "您需要定期到移植门诊复诊。",
    "sources": [],
    "gated": false
  },
  {
    "id": "ckm.independence.helps.1",
    "option": "ckm",
    "dimension": "independence",
    "tag": "helps",
    "en": "There is no machine or dialysis routine to manage. Care focuses on keeping you comfortable.",
    "zh": "不需要操作机器，也没有透析的固定程序。护理的重点是让您舒适。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "ckm.independence.harder.1",
    "option": "ckm",
    "dimension": "independence",
    "tag": "harder",
    "en": "As kidney function keeps going down, you may need more help from family and the care team over time.",
    "zh": "随着肾功能继续下降，您以后可能需要家人和医疗团队更多的帮助。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "pd.flexibility.helps.1",
    "option": "pd",
    "dimension": "flexibility",
    "tag": "helps",
    "en": "You can fit the fluid changes around your day, or use the machine at night.",
    "zh": "您可以按自己的时间安排换液，或者晚上用机器做。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.flexibility.harder.1",
    "option": "pd",
    "dimension": "flexibility",
    "tag": "harder",
    "en": "It happens every day. There are no days off.",
    "zh": "每天都要做，没有休息日。",
    "sources": [],
    "gated": false
  },
  {
    "id": "hd.flexibility.helps.1",
    "option": "hd",
    "dimension": "flexibility",
    "tag": "helps",
    "en": "A fixed routine that is easy to plan around: the same days and the same time slot each week.",
    "zh": "安排固定，容易提前计划：每星期同样的日子、同样的时段。",
    "sources": [
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "hd.flexibility.practical.1",
    "option": "hd",
    "dimension": "flexibility",
    "tag": "practical",
    "en": "At NKF centres you choose either Monday, Wednesday and Friday, or Tuesday, Thursday and Saturday, and a morning, afternoon or evening slot.",
    "zh": "在国家肾脏基金会的中心，您可以选择星期一、三、五，或星期二、四、六，并选择上午、下午或傍晚的时段。",
    "sources": [
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "hd.flexibility.harder.1",
    "option": "hd",
    "dimension": "flexibility",
    "tag": "harder",
    "en": "Three days a week are planned around your sessions.",
    "zh": "每星期有三天需要围绕透析来安排。",
    "sources": [
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "tx.flexibility.helps.1",
    "option": "tx",
    "dimension": "flexibility",
    "tag": "helps",
    "en": "Once the kidney is working, there is no dialysis schedule to follow.",
    "zh": "新肾脏开始运作后，就不需要按照透析时间表生活。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "tx.flexibility.harder.1",
    "option": "tx",
    "dimension": "flexibility",
    "tag": "harder",
    "en": "In the first months after the operation, you will have many clinic visits and blood tests.",
    "zh": "手术后的头几个月，需要经常复诊和验血。",
    "sources": [],
    "gated": false
  },
  {
    "id": "ckm.flexibility.helps.1",
    "option": "ckm",
    "dimension": "flexibility",
    "tag": "helps",
    "en": "There are no regular treatment sessions. Clinic visits are for check-ups and symptom care.",
    "zh": "没有固定的治疗时段。去门诊主要是复查和处理症状。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "ckm.flexibility.practical.1",
    "option": "ckm",
    "dimension": "flexibility",
    "tag": "practical",
    "en": "Visits and support may increase as your health changes.",
    "zh": "随着健康状况变化，复诊和支持可能会增加。",
    "sources": [],
    "gated": false
  },
  {
    "id": "pd.work.helps.1",
    "option": "pd",
    "dimension": "work",
    "tag": "helps",
    "en": "With the night-time machine, your days stay free for work or other responsibilities.",
    "zh": "使用夜间机器的话，白天可以空出来工作或处理其他事情。",
    "sources": [
      "NKF-PD",
      "VAN"
    ],
    "gated": false
  },
  {
    "id": "pd.work.practical.1",
    "option": "pd",
    "dimension": "work",
    "tag": "practical",
    "en": "Daytime fluid changes can be done at work if there is a clean, private place.",
    "zh": "如果工作的地方有干净、私密的空间，白天也可以在那里换液。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "hd.work.helps.1",
    "option": "hd",
    "dimension": "work",
    "tag": "helps",
    "en": "Evening sessions, or overnight dialysis at some NKF centres, can keep your daytime free.",
    "zh": "傍晚时段，或部分国家肾脏基金会中心的夜间透析，可以让您白天有空。",
    "sources": [
      "NKF-HD",
      "NKF-NOC"
    ],
    "gated": false
  },
  {
    "id": "hd.work.harder.1",
    "option": "hd",
    "dimension": "work",
    "tag": "harder",
    "en": "Daytime sessions take about 4 hours, plus travel, 3 times a week. This can clash with work.",
    "zh": "白天的透析每次大约四个小时，加上来回路程，每星期三次，可能会和工作时间冲突。",
    "sources": [
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "tx.work.helps.1",
    "option": "tx",
    "dimension": "work",
    "tag": "helps",
    "en": "Many people go back to work or study after they recover.",
    "zh": "很多人康复后可以重新工作或读书。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "tx.work.practical.1",
    "option": "tx",
    "dimension": "work",
    "tag": "practical",
    "en": "You will need time off for the operation and recovery.",
    "zh": "手术和康复期间需要请假。",
    "sources": [],
    "gated": false
  },
  {
    "id": "ckm.work.practical.1",
    "option": "ckm",
    "dimension": "work",
    "tag": "practical",
    "en": "There are no treatment sessions to fit around work, but working may become harder as your health changes.",
    "zh": "不需要为治疗调整工作时间，但随着健康状况变化，工作可能会变得比较困难。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "pd.travel.helps.1",
    "option": "pd",
    "dimension": "travel",
    "tag": "helps",
    "en": "PD can be done while you are away from home, with careful planning.",
    "zh": "只要事先做好安排，出门在外也可以做腹膜透析。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.travel.practical.1",
    "option": "pd",
    "dimension": "travel",
    "tag": "practical",
    "en": "Speak to your PD team early so supplies can be arranged. If you use the night machine, it needs to travel with you.",
    "zh": "请提早告诉腹膜透析团队，以便安排用品。如果您使用夜间机器，也需要带着它一起出门。",
    "sources": [],
    "gated": false
  },
  {
    "id": "hd.travel.harder.1",
    "option": "hd",
    "dimension": "travel",
    "tag": "harder",
    "en": "You need to book dialysis at a centre near where you are going, well ahead of time.",
    "zh": "您需要提早预约目的地附近的透析中心。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "hd.travel.practical.1",
    "option": "hd",
    "dimension": "travel",
    "tag": "practical",
    "en": "Longer trips, especially overseas, may be harder or more costly to arrange.",
    "zh": "较长的旅程，尤其是出国，可能比较难安排，费用也可能较高。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "tx.travel.helps.1",
    "option": "tx",
    "dimension": "travel",
    "tag": "helps",
    "en": "Once you have recovered and are stable, you can travel without arranging dialysis.",
    "zh": "康复并且情况稳定后，您出门旅行就不需要安排透析。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "tx.travel.practical.1",
    "option": "tx",
    "dimension": "travel",
    "tag": "practical",
    "en": "You need to bring your medicine with you and ask your team when it is safe to travel after the operation.",
    "zh": "出门时需要带上药物，并请医疗团队告诉您手术后什么时候可以安全出行。",
    "sources": [],
    "gated": false
  },
  {
    "id": "ckm.travel.practical.1",
    "option": "ckm",
    "dimension": "travel",
    "tag": "practical",
    "en": "You can travel if you feel well enough. Talk to your kidney team about your plans first.",
    "zh": "如果身体状况允许，您可以去旅行。出发前请先和肾脏团队商量。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "pd.time.helps.1",
    "option": "pd",
    "dimension": "time",
    "tag": "helps",
    "en": "There are no trips to a dialysis centre for treatment. You mainly go to the clinic for check-ups.",
    "zh": "不需要去透析中心做治疗，主要是回门诊复查。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.time.harder.1",
    "option": "pd",
    "dimension": "time",
    "tag": "harder",
    "en": "It takes time every day: several fluid changes of about half an hour each, or 8 to 10 hours on the machine at night.",
    "zh": "每天都需要花时间：白天换液几次，每次大约半小时；或晚上接上机器八到十个小时。",
    "sources": [
      "NKF-PD",
      "VAN"
    ],
    "gated": false
  },
  {
    "id": "hd.time.harder.1",
    "option": "hd",
    "dimension": "time",
    "tag": "harder",
    "en": "About 4 hours each session, 3 times a week, plus travel and waiting time.",
    "zh": "每次大约四个小时，每星期三次，还要加上来回和等候的时间。",
    "sources": [
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "hd.time.practical.1",
    "option": "hd",
    "dimension": "time",
    "tag": "practical",
    "en": "Overnight dialysis takes 6 to 7 hours, but it happens while you sleep.",
    "zh": "夜间透析需要六到七个小时，但是在您睡觉时进行。",
    "sources": [
      "NKF-NOC"
    ],
    "gated": false
  },
  {
    "id": "tx.time.helps.1",
    "option": "tx",
    "dimension": "time",
    "tag": "helps",
    "en": "After you recover, there are no dialysis sessions.",
    "zh": "康复以后，就不需要再做透析。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "tx.time.harder.1",
    "option": "tx",
    "dimension": "time",
    "tag": "harder",
    "en": "Waiting for a kidney from a donor who has passed away can take many years. In Singapore the average wait is about 8 years, and dialysis is usually needed while waiting.",
    "zh": "等待已故捐赠者的肾脏可能需要很多年。在新加坡，平均要等大约八年，等待期间通常需要透析。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "tx.time.practical.1",
    "option": "tx",
    "dimension": "time",
    "tag": "practical",
    "en": "A kidney from a living donor usually means a shorter wait.",
    "zh": "如果有活体捐赠者，等待的时间通常会比较短。",
    "sources": [
      "NKF-TX"
    ],
    "gated": true
  },
  {
    "id": "ckm.time.helps.1",
    "option": "ckm",
    "dimension": "time",
    "tag": "helps",
    "en": "There are no dialysis sessions. Your time on care is mainly regular clinic visits.",
    "zh": "没有透析时段。花在护理上的时间主要是定期复诊。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "pd.family.practical.1",
    "option": "pd",
    "dimension": "family",
    "tag": "practical",
    "en": "If you cannot do the treatment yourself, a family member or helper can be trained to do it.",
    "zh": "如果您自己没办法做，可以由家人或帮手学习后帮您做。",
    "sources": [
      "VAN",
      "RRT"
    ],
    "gated": false
  },
  {
    "id": "pd.family.practical.2",
    "option": "pd",
    "dimension": "family",
    "tag": "practical",
    "en": "NKF's PD nurses can visit your home to check on you and support you. Your hospital needs to refer you.",
    "zh": "国家肾脏基金会的腹膜透析护士可以上门探访和支持您，但需要由医院转介。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.family.harder.1",
    "option": "pd",
    "dimension": "family",
    "tag": "harder",
    "en": "If a family member does the treatment, it becomes part of their daily routine too.",
    "zh": "如果由家人帮忙做，这也会成为他们每天生活的一部分。",
    "sources": [],
    "gated": false
  },
  {
    "id": "hd.family.helps.1",
    "option": "hd",
    "dimension": "family",
    "tag": "helps",
    "en": "Staff at the centre do the treatment, so family do not need to help with it.",
    "zh": "由中心的工作人员做治疗，家人不需要帮忙操作。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "hd.family.practical.1",
    "option": "hd",
    "dimension": "family",
    "tag": "practical",
    "en": "Family may be needed to take you to and from the centre.",
    "zh": "可能需要家人接送您往返透析中心。",
    "sources": [],
    "gated": false
  },
  {
    "id": "tx.family.practical.1",
    "option": "tx",
    "dimension": "family",
    "tag": "practical",
    "en": "You will need help at home while you recover from the operation.",
    "zh": "手术后康复期间，您在家里需要有人帮忙。",
    "sources": [],
    "gated": false
  },
  {
    "id": "tx.family.practical.2",
    "option": "tx",
    "dimension": "family",
    "tag": "practical",
    "en": "A living donor is often a family member or friend. This is a personal decision for them too.",
    "zh": "活体捐赠者通常是家人或朋友，这对他们来说也是一个很个人的决定。",
    "sources": [
      "NKF-TX"
    ],
    "gated": true
  },
  {
    "id": "ckm.family.practical.1",
    "option": "ckm",
    "dimension": "family",
    "tag": "practical",
    "en": "Family often take on a bigger role as health changes. The supportive care team can support your family as well.",
    "zh": "随着健康状况变化，家人通常会承担更多照顾工作。支持性护理团队也可以帮助您的家人。",
    "sources": [
      "NKF-KSC"
    ],
    "gated": false
  },
  {
    "id": "pd.home.helps.1",
    "option": "pd",
    "dimension": "home",
    "tag": "helps",
    "en": "Most of your care happens at home.",
    "zh": "大部分的护理都在家里进行。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.home.harder.1",
    "option": "pd",
    "dimension": "home",
    "tag": "harder",
    "en": "You need a clean space for the treatment and room to store boxes of supplies.",
    "zh": "家里需要有干净的地方做治疗，也需要空间存放一箱箱的用品。",
    "sources": [
      "RRT"
    ],
    "gated": false
  },
  {
    "id": "pd.home.practical.1",
    "option": "pd",
    "dimension": "home",
    "tag": "practical",
    "en": "PD nurses can check your home and help you set it up.",
    "zh": "腹膜透析护士可以评估您的家，并帮助您布置。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "hd.home.helps.1",
    "option": "hd",
    "dimension": "home",
    "tag": "helps",
    "en": "No equipment or supplies are kept at home, and nurses are nearby during treatment.",
    "zh": "家里不需要放任何器材或用品，治疗时也有护士在旁。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "hd.home.harder.1",
    "option": "hd",
    "dimension": "home",
    "tag": "harder",
    "en": "You need to go to the centre for every session.",
    "zh": "每次透析都需要到中心去。",
    "sources": [
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "tx.home.practical.1",
    "option": "tx",
    "dimension": "home",
    "tag": "practical",
    "en": "No treatment equipment is needed at home.",
    "zh": "家里不需要任何治疗器材。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "ckm.home.helps.1",
    "option": "ckm",
    "dimension": "home",
    "tag": "helps",
    "en": "Care aims to keep you comfortable at home and avoid hospital stays that are not needed.",
    "zh": "护理的目标是让您在家里舒适地生活，避免不必要的住院。",
    "sources": [
      "NKF-KSC",
      "MYK"
    ],
    "gated": false
  },
  {
    "id": "pd.body.practical.1",
    "option": "pd",
    "dimension": "body",
    "tag": "practical",
    "en": "A small operation places a soft tube in your tummy.",
    "zh": "需要一个小手术，在肚子里放一条软管。",
    "sources": [
      "VAN",
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.body.helps.1",
    "option": "pd",
    "dimension": "body",
    "tag": "helps",
    "en": "No needles are used.",
    "zh": "不需要打针。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "pd.body.harder.1",
    "option": "pd",
    "dimension": "body",
    "tag": "harder",
    "en": "Doing the fluid changes needs steady hands and good eyesight, or a helper who can do it.",
    "zh": "换液需要手稳、视力好，或者有人帮忙做。",
    "sources": [],
    "gated": false
  },
  {
    "id": "pd.body.practical.2",
    "option": "pd",
    "dimension": "body",
    "tag": "practical",
    "en": "Some people feel full in the tummy.",
    "zh": "有些人会觉得肚子胀。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "hd.body.practical.1",
    "option": "hd",
    "dimension": "body",
    "tag": "practical",
    "en": "A small operation on your arm prepares a blood vessel for dialysis.",
    "zh": "需要在手臂上做一个小手术，为透析准备好血管。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "hd.body.harder.1",
    "option": "hd",
    "dimension": "body",
    "tag": "harder",
    "en": "Two needles are put into your arm at every session.",
    "zh": "每次透析都要在手臂上插两根针。",
    "sources": [
      "NKF-HD"
    ],
    "gated": false
  },
  {
    "id": "hd.body.harder.2",
    "option": "hd",
    "dimension": "body",
    "tag": "harder",
    "en": "Some people feel tired or dizzy, or get cramps, during or after a session.",
    "zh": "有些人在透析时或透析后会觉得疲倦、头晕或抽筋。",
    "sources": [
      "NKF-NOC"
    ],
    "gated": false
  },
  {
    "id": "tx.body.harder.1",
    "option": "tx",
    "dimension": "body",
    "tag": "harder",
    "en": "It is a major operation, with a hospital stay of about 5 to 7 days.",
    "zh": "这是一个大手术，需要住院大约五到七天。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "tx.body.harder.2",
    "option": "tx",
    "dimension": "body",
    "tag": "harder",
    "en": "Anti-rejection medicine can have side effects. Your team will explain them.",
    "zh": "抗排斥药物可能有副作用，医疗团队会向您说明。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "tx.body.practical.1",
    "option": "tx",
    "dimension": "body",
    "tag": "practical",
    "en": "Doctors first check your overall health to see if a transplant is safe for you.",
    "zh": "医生会先检查您的整体健康，看看移植对您是否安全。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "ckm.body.helps.1",
    "option": "ckm",
    "dimension": "body",
    "tag": "helps",
    "en": "No operations are needed.",
    "zh": "不需要做任何手术。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "ckm.body.practical.1",
    "option": "ckm",
    "dimension": "body",
    "tag": "practical",
    "en": "Symptoms such as tiredness, itch or poor appetite may increase over time. Your team will help you manage them.",
    "zh": "疲倦、瘙痒或胃口差等症状可能会慢慢增加，医疗团队会帮您处理。",
    "sources": [
      "NKF-KSC"
    ],
    "gated": false
  },
  {
    "id": "pd.comfort.helps.1",
    "option": "pd",
    "dimension": "comfort",
    "tag": "helps",
    "en": "It works slowly and all the time, like your own kidneys. Many people find it gentler, with fewer food limits than haemodialysis.",
    "zh": "它像自己的肾脏一样，慢慢地、持续地工作。很多人觉得比较温和，饮食限制也比血液透析少。",
    "sources": [
      "NKF-PD"
    ],
    "gated": false
  },
  {
    "id": "hd.comfort.harder.1",
    "option": "hd",
    "dimension": "comfort",
    "tag": "harder",
    "en": "There are more limits on food and drink between sessions.",
    "zh": "两次透析之间，饮食和喝水的限制比较多。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "hd.comfort.practical.1",
    "option": "hd",
    "dimension": "comfort",
    "tag": "practical",
    "en": "Overnight dialysis works more slowly, which can mean fewer problems such as dizziness and cramps for people who are suitable.",
    "zh": "夜间透析比较慢，对适合的人来说，头晕、抽筋等问题可能会比较少。",
    "sources": [
      "NKF-NOC"
    ],
    "gated": false
  },
  {
    "id": "tx.comfort.helps.1",
    "option": "tx",
    "dimension": "comfort",
    "tag": "helps",
    "en": "There are fewer limits on food and drink, and many people feel much better.",
    "zh": "饮食和喝水的限制较少，很多人会觉得身体好很多。",
    "sources": [
      "NKF-TX"
    ],
    "gated": false
  },
  {
    "id": "ckm.comfort.helps.1",
    "option": "ckm",
    "dimension": "comfort",
    "tag": "helps",
    "en": "Care focuses on your comfort and quality of life.",
    "zh": "护理的重点是您的舒适和生活质量。",
    "sources": [
      "KHA-G",
      "NKF-KSC"
    ],
    "gated": false
  },
  {
    "id": "ckm.comfort.practical.1",
    "option": "ckm",
    "dimension": "comfort",
    "tag": "practical",
    "en": "Some changes to what you eat and drink may still be needed.",
    "zh": "可能仍然需要调整饮食和喝水。",
    "sources": [
      "KHA-G"
    ],
    "gated": false
  },
  {
    "id": "common.longevity.ask-team.1",
    "option": "common",
    "dimension": "longevity",
    "tag": "ask-team",
    "en": "How each choice may affect how long you live depends on your age and your other health conditions. Your kidney doctor can explain this for you personally.",
    "zh": "每种选择会怎样影响寿命，要看您的年龄和其他健康状况。肾科医生可以根据您的情况为您说明。",
    "sources": [
      "RRT",
      "MYK"
    ],
    "gated": false
  },
  {
    "id": "common.cost.ask-team.1",
    "option": "common",
    "dimension": "cost",
    "tag": "ask-team",
    "en": "Costs and financial help differ for each option and depend on your situation. Your medical social worker or care team can explain what applies to you.",
    "zh": "每种方式的费用和经济援助都不一样，也要看您的情况。医疗社工或医疗团队可以告诉您适用的安排。",
    "sources": [
      "NKF-TX",
      "NKF-PD"
    ],
    "gated": false
  }
] as const;
